---
{
   "environment": {
      "DEFAULT_WORKSPACE": "/drone/src"
   },
   "kind": "pipeline",
   "name": "Mega-Linter",
   "steps": [
      {
         "image": "oxsecurity/megalinter-python:v6",
         "name": "Lint"
      }
   ],
   "workspace": {
      "path": "/drone/src"
   }
}
---
{
   "kind": "pipeline",
   "name": "python3.7",
   "steps": [
      {
         "commands": [
            "python3 -m pip install --upgrade pip",
            "python3 -m pip install --upgrade pipx",
            "python3 -m pipx ensurepath",
            "python3 -m pipx run pipenv --python 3.7",
            "python3 -m pipx run pipenv install --dev --skip-lock",
            "python3 -m pipx run pipenv run lint",
            "python3 -m pipx run pipenv run test"
         ],
         "image": "python:3.7",
         "name": "test",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            },
            {
               "name": "pipenv-cache",
               "path": "/root/.local/share/virtualenvs"
            }
         ]
      },
      {
         "commands": [
            "python3 -m pip install --upgrade pip",
            "python3 -m pip install --upgrade pipx",
            "python3 -m pipx ensurepath",
            "python3 -m pipx run pipenv run codecov"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov-upload-token"
            }
         },
         "failure": "ignore",
         "image": "python:3.7",
         "name": "codecov",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            },
            {
               "name": "pipenv-cache",
               "path": "/root/.local/share/virtualenvs"
            }
         ]
      }
   ],
   "volumes": [
      {
         "name": "pip-cache",
         "temp": { }
      },
      {
         "name": "pipenv-cache",
         "temp": { }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "python3.8",
   "steps": [
      {
         "commands": [
            "python3 -m pip install --upgrade pip",
            "python3 -m pip install --upgrade pipx",
            "python3 -m pipx ensurepath",
            "python3 -m pipx run pipenv --python 3.8",
            "python3 -m pipx run pipenv install --dev --skip-lock",
            "python3 -m pipx run pipenv run lint",
            "python3 -m pipx run pipenv run test"
         ],
         "image": "python:3.8",
         "name": "test",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            },
            {
               "name": "pipenv-cache",
               "path": "/root/.local/share/virtualenvs"
            }
         ]
      },
      {
         "commands": [
            "python3 -m pip install --upgrade pip",
            "python3 -m pip install --upgrade pipx",
            "python3 -m pipx ensurepath",
            "python3 -m pipx run pipenv run codecov"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov-upload-token"
            }
         },
         "failure": "ignore",
         "image": "python:3.8",
         "name": "codecov",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            },
            {
               "name": "pipenv-cache",
               "path": "/root/.local/share/virtualenvs"
            }
         ]
      }
   ],
   "volumes": [
      {
         "name": "pip-cache",
         "temp": { }
      },
      {
         "name": "pipenv-cache",
         "temp": { }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "python3.9",
   "steps": [
      {
         "commands": [
            "python3 -m pip install --upgrade pip",
            "python3 -m pip install --upgrade pipx",
            "python3 -m pipx ensurepath",
            "python3 -m pipx run pipenv --python 3.9",
            "python3 -m pipx run pipenv install --dev --skip-lock",
            "python3 -m pipx run pipenv run lint",
            "python3 -m pipx run pipenv run test"
         ],
         "image": "python:3.9",
         "name": "test",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            },
            {
               "name": "pipenv-cache",
               "path": "/root/.local/share/virtualenvs"
            }
         ]
      },
      {
         "commands": [
            "python3 -m pip install --upgrade pip",
            "python3 -m pip install --upgrade pipx",
            "python3 -m pipx ensurepath",
            "python3 -m pipx run pipenv run codecov"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov-upload-token"
            }
         },
         "failure": "ignore",
         "image": "python:3.9",
         "name": "codecov",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            },
            {
               "name": "pipenv-cache",
               "path": "/root/.local/share/virtualenvs"
            }
         ]
      }
   ],
   "volumes": [
      {
         "name": "pip-cache",
         "temp": { }
      },
      {
         "name": "pipenv-cache",
         "temp": { }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "python3.10",
   "steps": [
      {
         "commands": [
            "python3 -m pip install --upgrade pip",
            "python3 -m pip install --upgrade pipx",
            "python3 -m pipx ensurepath",
            "python3 -m pipx run pipenv --python 3.10",
            "python3 -m pipx run pipenv install --dev --skip-lock",
            "python3 -m pipx run pipenv run lint",
            "python3 -m pipx run pipenv run test"
         ],
         "image": "python:3.10",
         "name": "test",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            },
            {
               "name": "pipenv-cache",
               "path": "/root/.local/share/virtualenvs"
            }
         ]
      },
      {
         "commands": [
            "python3 -m pip install --upgrade pip",
            "python3 -m pip install --upgrade pipx",
            "python3 -m pipx ensurepath",
            "python3 -m pipx run pipenv run codecov"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov-upload-token"
            }
         },
         "failure": "ignore",
         "image": "python:3.10",
         "name": "codecov",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            },
            {
               "name": "pipenv-cache",
               "path": "/root/.local/share/virtualenvs"
            }
         ]
      }
   ],
   "volumes": [
      {
         "name": "pip-cache",
         "temp": { }
      },
      {
         "name": "pipenv-cache",
         "temp": { }
      }
   ]
}
---
{
   "depends_on": [
      "Mega-Linter",
      "python3.7",
      "python3.8",
      "python3.9",
      "python3.10"
   ],
   "kind": "pipeline",
   "name": "Package",
   "steps": [
      {
         "commands": [
            "python3 -m pip install --upgrade pip",
            "python3 -m pip install --upgrade pipx",
            "python3 -m pipx ensurepath",
            "python3 -m pipx run pipenv --three",
            "python3 -m pipx run pipenv install --dev --skip-lock",
            "python3 -m pipx run pipenv run clean",
            "python3 -m pipx run pipenv run package",
            "python3 -m pipx run pipenv run check-package"
         ],
         "image": "python:3",
         "name": "Package",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            },
            {
               "name": "pipenv-cache",
               "path": "/root/.local/share/virtualenvs"
            }
         ]
      }
   ],
   "volumes": [
      {
         "name": "pip-cache",
         "temp": { }
      },
      {
         "name": "pipenv-cache",
         "temp": { }
      }
   ]
}
---
{
   "data": "9ooebQakEh6XD6G3L3yvCTKKQ9pxdI8cpPMfGweOOmThfG1EEygi8uZSaAmxTGKxRgrT8qgqkSFyv7edrRAkIw==",
   "kind": "secret",
   "name": "codecov-upload-token"
}
...
