---
{
   "kind": "pipeline",
   "name": "python2.7",
   "steps": [
      {
         "commands": [
            "pip install --upgrade pipenv",
            "pipenv install --dev --skip-lock",
            "pipenv run python setup.py lint",
            "pipenv run python setup.py test --addopts --cov"
         ],
         "environment": {
            "PIPENV_VENV_IN_PROJECT": 1
         },
         "image": "python:2.7",
         "name": "test",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            }
         ]
      },
      {
         "commands": [
            "pip install --upgrade pipenv",
            "pipenv run codecov"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov-upload-token"
            },
            "PIPENV_VENV_IN_PROJECT": 1
         },
         "failure": "ignore",
         "image": "python:2.7",
         "name": "codecov",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            }
         ]
      }
   ],
   "volumes": [
      {
         "name": "pip-cache",
         "temp": { }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "python3.5",
   "steps": [
      {
         "commands": [
            "pip install --upgrade pipenv",
            "pipenv install --dev --skip-lock",
            "pipenv run python setup.py lint",
            "pipenv run python setup.py test --addopts --cov"
         ],
         "environment": {
            "PIPENV_VENV_IN_PROJECT": 1
         },
         "image": "python:3.5",
         "name": "test",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            }
         ]
      },
      {
         "commands": [
            "pip install --upgrade pipenv",
            "pipenv run codecov"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov-upload-token"
            },
            "PIPENV_VENV_IN_PROJECT": 1
         },
         "failure": "ignore",
         "image": "python:3.5",
         "name": "codecov",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            }
         ]
      }
   ],
   "volumes": [
      {
         "name": "pip-cache",
         "temp": { }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "python3.6",
   "steps": [
      {
         "commands": [
            "pip install --upgrade pipenv",
            "pipenv install --dev --skip-lock",
            "pipenv run python setup.py lint",
            "pipenv run python setup.py test --addopts --cov"
         ],
         "environment": {
            "PIPENV_VENV_IN_PROJECT": 1
         },
         "image": "python:3.6",
         "name": "test",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            }
         ]
      },
      {
         "commands": [
            "pip install --upgrade pipenv",
            "pipenv run codecov"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov-upload-token"
            },
            "PIPENV_VENV_IN_PROJECT": 1
         },
         "failure": "ignore",
         "image": "python:3.6",
         "name": "codecov",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            }
         ]
      }
   ],
   "volumes": [
      {
         "name": "pip-cache",
         "temp": { }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "python3.7",
   "steps": [
      {
         "commands": [
            "pip install --upgrade pipenv",
            "pipenv install --dev --skip-lock",
            "pipenv run python setup.py lint",
            "pipenv run python setup.py test --addopts --cov"
         ],
         "environment": {
            "PIPENV_VENV_IN_PROJECT": 1
         },
         "image": "python:3.7",
         "name": "test",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            }
         ]
      },
      {
         "commands": [
            "pip install --upgrade pipenv",
            "pipenv run codecov"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov-upload-token"
            },
            "PIPENV_VENV_IN_PROJECT": 1
         },
         "failure": "ignore",
         "image": "python:3.7",
         "name": "codecov",
         "volumes": [
            {
               "name": "pip-cache",
               "path": "/root/.cache/pip"
            }
         ]
      }
   ],
   "volumes": [
      {
         "name": "pip-cache",
         "temp": { }
      }
   ]
}
---
{
   "data": "9ooebQakEh6XD6G3L3yvCTKKQ9pxdI8cpPMfGweOOmThfG1EEygi8uZSaAmxTGKxRgrT8qgqkSFyv7edrRAkIw==",
   "kind": "secret",
   "name": "codecov-upload-token"
}
...
