APPLY_FIXES: none
SHOW_ELAPSED_TIME: true
IGNORE_GITIGNORED_FILES: true
DISABLE:
  - SPELL
FILEIO_REPORTER: true
FILTER_REGEX_EXCLUDE: \.drone\.yml
PYTHON_BLACK_CONFIG_FILE: LINTER_DEFAULT
PYTHON_ISORT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_BANDIT_CONFIG_FILE: .bandit.yml
# TODO: Replace it with `LINTER_DEFAULT`
#
# Bandit in Mega-Linter has not yet supported `pyproject.toml`.
#
# https://github.com/PyCQA/bandit/commit/44f5c416cc0b7d62ca55b78e90bd1f7ee3d16082
# https://github.com/PyCQA/bandit/pull/401
