APPLY_FIXES: none
SHOW_ELAPSED_TIME: true
IGNORE_GITIGNORED_FILES: true
DISABLE:
  - SPELL
FILEIO_REPORTER: true
FILTER_REGEX_EXCLUDE: \.drone\.yml
PYTHON_BLACK_CONFIG_FILE: LINTER_DEFAULT
PYTHON_ISORT_CONFIG_FILE: LINTER_DEFAULT
