language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
# For Python 3.7
#
# https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-425867404
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
cache:
  pip: true

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1

install:
  - pip install --upgrade pipenv
  - pipenv install --dev

script:
  - pipenv run flake8
  - pipenv run pytest --cov

after_success:
  - pipenv run codecov
