language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
cache:
  pip: true

install:
  - pip install --upgrade pipenv
  - pipenv install --dev

script:
  - pipenv run flake8
  - pipenv run pytest --cov

after_success:
  - pipenv run codecov
