version: 2.1

orbs:
  python: circleci/python@3.1.0
  codecov: codecov/codecov@5.4.3

jobs:
  MegaLinter:
    docker:
      - image: oxsecurity/megalinter-python:v8
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo "export CI_JOB_URL=$CIRCLE_BUILD_URL" >> "$BASH_ENV"
            # Export `CI_JOB_URL` for MegaLinter API Reporter
            echo "export DEFAULT_WORKSPACE=$CIRCLE_WORKING_DIRECTORY" >> "$BASH_ENV"
            . "$BASH_ENV"
      - run:
          name: Run MegaLinter
          command: |
            sh /entrypoint.sh
      - store_artifacts:
          path: megalinter-reports
  test:
    parameters:
      python-version:
        type: string
    executor:
      name: python/default
      tag: << parameters.python-version >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: lint
          command: |
            poetry run poe lint
      - run:
          name: test
          command: |
            poetry run poe test
      - codecov/upload
      - run:
          name: packaging test
          command: |
            set +e
            poetry run poe clean
            poetry build
            poetry run poe check-package
        # Figure out which versions of Python work well with Invoke, since
        # Invoke may not work with recent Python releases.
        #
        # https://github.com/pyinvoke/invoke/issues/833#issuecomment-1293148106
        # https://github.com/pyinvoke/invoke/pull/458
        # https://github.com/pyinvoke/invoke/pull/606

workflows:
  CI:
    jobs:
      - MegaLinter:
          context: megalinter
      - test:
          matrix:
            parameters:
              python-version:
                - "3.9"
                - "3.10"
                - "3.11"
                - "3.12"
                - "3.13"
          context: test
